postgres:
  protocol: ""
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: postgres
  sslmode: disable
  timeout: 15
  max_open_conns: 0
  max_idle_conns: 0
  max_conn_lifetime: 0
  google_auth_file: ""
env: dev
port: 8080
email:
  host: smtp.gmail.com
  port: 587
  username: shinichi24567@gmail.com
  password: shinichi24567123
  encrypt: tls